/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: HyliGun174 (https://sketchfab.com/HyliGun174)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/robot-d129be6351904825af790cbcb452c5c7
Title: Robot
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot(props) {
  const { nodes, materials } = useGLTF('/assets/models/robot.glb');

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Sphere006_Material_1_0.geometry}
            material={materials.Material_1}
            position={[2.216, 195.585, 0.002]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/robot.glb');

